import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Bot, User, ChevronDown, ChevronRight, Terminal } from 'lucide-react';
export function ChatArea({ messages }) {
    return (_jsxs("div", { className: "flex flex-col gap-6 max-w-4xl mx-auto w-full", children: [messages.map((msg) => (_jsx(MessageItem, { msg: msg }, msg.id))), messages.length === 0 && (_jsxs("div", { className: "flex flex-col items-center justify-center h-full text-slate-500 mt-20", children: [_jsx(Bot, { size: 48, className: "mb-4 opacity-50" }), _jsx("p", { children: "Le salon est vide. Dites quelque chose !" })] }))] }));
}
function MessageItem({ msg }) {
    const isUser = msg.sender === 'User';
    const [showThought, setShowThought] = useState(false);
    return (_jsxs("div", { className: `flex gap-4 ${isUser ? 'flex-row-reverse' : ''}`, children: [_jsx("div", { className: `w-10 h-10 rounded-full flex items-center justify-center shrink-0 shadow-sm ${isUser ? 'bg-indigo-600 text-white' : 'bg-slate-700 text-emerald-400'}`, children: isUser ? _jsx(User, { size: 20 }) : _jsx(Bot, { size: 20 }) }), _jsxs("div", { className: `flex flex-col gap-2 max-w-[80%] ${isUser ? 'items-end' : 'items-start'}`, children: [_jsxs("div", { className: "flex items-baseline gap-2 mx-1", children: [_jsx("span", { className: "font-semibold text-sm text-slate-300", children: msg.sender }), _jsx("span", { className: "text-xs text-slate-500", children: new Date(msg.timestamp).toLocaleTimeString() })] }), _jsxs("div", { className: `p-4 rounded-2xl shadow-sm ${isUser
                            ? 'bg-indigo-600 text-white rounded-tr-none'
                            : 'bg-slate-800 text-slate-200 rounded-tl-none border border-slate-700'}`, children: [msg.thought && !isUser && (_jsxs("div", { className: "mb-3", children: [_jsxs("button", { onClick: () => setShowThought(!showThought), className: "flex items-center gap-1 text-xs font-medium text-slate-400 hover:text-slate-300 transition-colors", children: [showThought ? _jsx(ChevronDown, { size: 14 }) : _jsx(ChevronRight, { size: 14 }), "Chain of Thought"] }), showThought && (_jsx("div", { className: "mt-2 p-3 bg-slate-900/50 rounded-md text-sm text-slate-400 border border-slate-700/50 font-mono text-xs whitespace-pre-wrap", children: msg.thought }))] })), _jsx("div", { className: "whitespace-pre-wrap leading-relaxed", children: msg.text }), msg.action && (_jsxs("div", { className: "mt-3 p-3 bg-emerald-900/20 border border-emerald-500/20 rounded-md flex items-start gap-2", children: [_jsx(Terminal, { size: 16, className: "text-emerald-500 mt-0.5 shrink-0" }), _jsxs("div", { children: [_jsx("div", { className: "text-xs font-semibold text-emerald-400 mb-1", children: msg.action.type }), _jsx("pre", { className: "text-xs text-emerald-300/70 overflow-x-auto", children: JSON.stringify(msg.action.payload, null, 2) })] })] }))] })] })] }));
}
